# Generated by Django 2.0.13 on 2020-09-10 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_assetlayermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlayermodel',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
