# Generated by Django 2.0.13 on 2020-09-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_assetlayermodel_cdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegrationLayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engtool', models.CharField(max_length=100)),
                ('filesize', models.FloatField(verbose_name=0)),
                ('databasetype', models.CharField(max_length=10)),
                ('humanmachineinterface', models.IntegerField()),
                ('plcslaves', models.IntegerField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'IntegrationTable',
            },
        ),
    ]
