# Generated by Django 2.0.13 on 2020-09-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userintegrationlayermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegrationlayermodel',
            name='filesize',
            field=models.FloatField(),
        ),
    ]
