# Generated by Django 2.0.13 on 2020-09-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200910_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFunctionalLayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productionmodel', models.CharField(max_length=100)),
                ('modelbuilding', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FunctionalTable',
            },
        ),
    ]
